### ISSUE TITLE
A Tip

### ISSUE THREAD

**Issue by evinugur** [FRCTeam1073-TheForceTeam/RookiePreseason2014#1]
You should probably not branch off the repository for each preseason project, instead just add a folder at the root of the repo and commit your code in there so rookies and other newcomers have an easier time accessing things and it's clearer at a glance what the project contains.
## 

saw this in my GH feed, figured I'd comment. Good luck next year :)

**Comment by TechnoD11** [comment]
Alright, good tip. I just took a quick Github tutorial (wasn’t very good at it) and figured I would try out how branching works. It would be confusing to the rookies though.

Thanks Evin

Derek
